export const LoginType = {
  AUTHENTICATE: 'AUTHENTICATE',
  LOGIN_SUCCESSFUL: 'LOGIN_SUCCESSFUL',
  LOGOUT_SUCCESSFUL: 'LOGOUT_SUCCESSFUL'
};

export const ErrorType = {
  ERROR_LOG: 'ERROR_LOG'
};

export const DashboardType = {
  GLOBAL_SEARCH_TEXT: 'GLOBAL_SEARCH_TEXT',
  TOGGLE_GRID_VIEW: 'TOGGLE_GRID_VIEW',
  HANDLE_SNACKBAR: 'HANDLE_SNACKBAR'
  // SET_IS_LOADING: 'SET_IS_LOADING',
  // RESET_IS_LOADING: 'RESET_IS_LOADING'
};

export const UsersType = {
  FETCHED_USERS: 'FETCHED_USERS',
  ADDED_USER: 'ADDED_USER',
  DELETED_USERS: 'DELETED_USERS'
};

export const Branch = {
  CREATE_BRANCH: 'CREATE_BRANCH',
  FETCH_BRANCHES: 'FETCH_BRANCHES',
  UPDATE_BRANCH: 'UPDATE_BRANCH',
  DELETE_BRANCHES: 'DELETE_BRANCHES'
};

export const Employee = {
  CREATE_EMPLOYEE: 'CREATE_EMPLOYEE',
  FETCH_EMPLOYEE: 'FETCH_EMPLOYEE'
};

export const Program = {
  CREATE_PROGRAM: 'CREATE_PROGRAM',
  FETCH_PROGRAM: 'FETCH_PROGRAM'
};

export const FeeCode = {
  CREATE_FEE_CODE: 'CREATE_FEE_CODE',
  FETCH_FEE_CODE: 'FETCH_FEE_CODE'
};

export const gstRates = {
  CREATE_GST_RATE: 'CREATE_GST_RATE',
  FETCH_GST_RATE: 'FETCH_GST_RATE'
};

export const FeeStructure = {
  CREATE_FEE_STRUCTURE: 'CREATE_FEE_STRUCTURE',
  FETCH_FEE_STRUCTURE: 'FETCH_FEE_STRUCTURE'
};

export const Course = {
  CREATE_COURSE: 'CREATE_COURSE',
  FETCH_COURSE: 'FETCH_COURSE'
};

export const CourseDuration = {
  CREATE_COURSE_DURATION: 'CREATE_COURSE_DURATION',
  FETCH_COURSE_DURATION: 'FETCH_COURSE_DURATION'
};

export const Batch = {
  CREATE_BATCH: 'CREATE_BATCH',
  FETCH_BATCH: 'FETCH_BATCH'
};

export const Building = {
  CREATE_BUILDING: 'CREATE_BUILDING',
  FETCH_BUILDINGS: 'FETCH_BUILDINGS',
  UPDATE_BUILDING: 'UPDATE_BUILDING'
};

export const Cities = {
  FETCH_CITIES: 'FETCH_CITIES',
  CREATE_CITIES: 'CREATE_CITIES',
  UPDATE_CITY: 'UPDATE_CITY'
};

export const States = {
  FETCH_STATES: 'FETCH_STATES',
  CREATE_STATE: 'CREATE_STATE',
  FETCH_STATES_CITIES: 'FETCH_STATES_CITIES',
  UPDATE_STATE: 'UPDATE_STATE'
};

export const Organisations = {
  FETCH_ORGANISATIONS: 'FETCH_ORGANISATIONS',
  CREATE_ORGANISATION: 'CREATE_ORGANISATION',
  UPDATE_ORGANISATION: 'UPDATE_ORGANISATION',
  SET_CURRENT_ORGANISATION: 'SET_CURRENT_ORGANISATION'
};

export const Campus = {
  CREATE_CAMPUS: 'CREATE_CAMPUS',
  FETCH_CAMPUSES: 'FETCH_CAMPUSES',
  UPDATE_CAMPUS: 'UPDATE_CAMPUS',
  DELETE_CAMPUSES: 'DELETE_CAMPUSES'
};

export const Room = {
  CREATE_ROOM: 'CREATE_ROOM',
  FETCH_ROOMS: 'FETCH_ROOMS',
  UPDATE_ROOM: 'UPDATE_ROOM',
  DELETE_ROOMS: 'DELETE_ROOMS'
};

export const SourceType = {
  FETCH_SOURCETYPES: 'FETCH_SOURCETYPES',
  CREATE_SOURCETYPE: 'CREATE_SOURCETYPE',
  UPDATE_SOURCETYPE: 'UPDATE_SOURCETYPE'
};

export const AgencyCode = {
  FETCH_AGENCYCODES: 'FETCH_AGENCYCODES',
  CREATE_AGENCY: 'CREATE_AGENCY',
  UPDATE_AGENCY: 'UPDATE_AGENCY'
};

export const PreAdmission = {
  FETCH_PREADMISSION_DATA: 'FETCH_PREADMISSION_DATA',
  FETCH_STUDENTS_BASEDON_FILTER: 'FETCH_STUDENTS_BASEDON_FILTER',
  CREATE_PREADMISSION: 'CREATE_PREADMISSION',
  UPDATE_PREADMISSION: 'UPDATE_PREADMISSION',
  DELETE_PREADMISSION: 'DELETE_PREADMISSION',
  ALLOCATE_TO_EMPLOYEE: 'ALLOCATE_TO_EMPLOYEE',
  ACCEPT_OR_REJECT_ENQUIRY: 'ACCEPT_REJECT_ENQUIRY'
};

export const ResponseType = {
  FETCH_RESPONSE_TYPES: 'FETCH_RESPONSE_TYPES'
};
