export const LoginType = {
  AUTHENTICATE: 'AUTHENTICATE',
  LOGIN_SUCCESSFUL: 'LOGIN_SUCCESSFUL',
  LOGOUT_SUCCESSFUL: 'LOGOUT_SUCCESSFUL'
};

export const ErrorType = {
  ERROR_LOG: 'ERROR_LOG'
};

export const UsersType = {
  FETCHED_USERS: 'FETCHED_USERS',
  ADDED_USER: 'ADDED_USER',
  DELETED_USERS: 'DELETED_USERS'
};

export const Branch = {
  CREATE_BRANCH: 'CREATE_BRANCH',
  FETCH_BRANCHES: 'FETCH_BRANCHES'
};

export const Cities = {
  FETCH_CITIES: 'FETCH_CITIES'
};

export const States = {
  FETCH_STATES: 'FETCH_STATES'
};

export const Campus = {
  CREATE_CAMPUS: 'CREATE_CAMPUS',
  FETCH_CAMPUSES: 'FETCH_CAMPUSES'
};
